---
version: 1.0.10
slug: linus
name: Linus
description: Linus OpenAI pipeline
url: https://github.com/oleander/ha-openai-rs
arch: [amd64]
init: false
schema:
  openai_api_key: string
ports:
  10200/tcp: 10200
homeassistant: 2023.12.0
homeassistant_api: true
legacy: true


