single_line_let_else_max_width = 0
match_block_trailing_comma = false
enum_discrim_align_threshold = 180
struct_field_align_threshold = 180
fn_params_layout = "Tall"
use_field_init_shorthand = true
struct_lit_single_line = false
imports_granularity = "Module"
imports_layout = "Mixed"
force_multiline_blocks = true
# use_small_heuristics = "Max"
normalize_comments = false
reorder_impl_items = true
imports_indent = "Block"
where_single_line = true
trailing_comma = "Never"
reorder_modules = false
reorder_imports = false
newline_style = "Auto"
group_imports = "StdExternalCrate"
fn_call_width = 180
hard_tabs = false
max_width = 220
tab_spaces = 2
